g-auto/Controllers/CareersController.cs
using g_auto.DAL;
using g_auto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace g_auto.Controllers
{
    
    public class CareersController : Controller
    {
        DBContext db = new DBContext();
        // GET: Careers
        public ActionResult Index()
        {


            #region Cart list

            HttpCookie cookieCart = Request.Cookies["Cart"];
            List<string> CartList = new List<string>();
            if (cookieCart != null)
            {
                CartList = cookieCart.Value.Split(',').ToList();
                CartList.RemoveAt(CartList.Count - 1);

                ViewBag.CartList = CartList;
                ViewBag.CartListCount = CartList.Count;
            }
            else
            {
                ViewBag.CartListCount = 0;
            }

            List<Product> products = new List<Product>();

            foreach (var item in CartList)
            {
                foreach (var prd in db.Products.Include("ProductImages").Include("Admin").Include("ProductToCategory").Include("ProductToCategory.ProductCategory").ToList())
                {
                    if (Convert.ToInt32(item.Split('-')[0]) == prd.Id)
                    {
                        prd.Count = Convert.ToDecimal(item.Split('-')[1]);
                        products.Add(prd);
                    }
                }

            }
            #endregion

            ViewBag.Products = products;
            ViewBag.CareersPage = true;
            ViewBag.Blogs = db.Blog.Where(c => c.isActive).OrderByDescending(c => c.PostDate).Take(3).ToList();
            ViewBag.Address = db.Layout.FirstOrDefault().Address;
            ViewBag.Phone = db.Layout.FirstOrDefault().Phone;
            ViewBag.Email = db.Layout.FirstOrDefault().Email;
            ViewBag.FooterLogo = db.Layout.FirstOrDefault().LogoFooter;
            ViewBag.HeaderLogo = db.Layout.FirstOrDefault().Logo;
            List<Vacancy> xdb = db.Vacancies.Where(c => c.isActive).ToList();

            return View(xdb);
        }

        public ActionResult Details(int id)
        {

            #region Cart list

            HttpCookie cookieCart = Request.Cookies ["Cart"];
            List<string> CartList = new List<string>();
            if (cookieCart != null)
            {
                CartList = cookieCart.Value.Split(',').ToList();
        CartList.RemoveAt(CartList.Count - 1);

                ViewBag.CartList = CartList;
                ViewBag.CartListCount = CartList.Count;
            }
            else
            {
                ViewBag.CartListCount = 0;
            }

List<Product> products = new List<Product>();

foreach (var item in CartList)
{
    foreach (var prd in db.Products.Include("ProductImages").Include("Admin").Include("ProductToCategory").Include("ProductToCategory.ProductCategory").ToList())
    {
        if (Convert.ToInt32(item.Split('-')[0]) == prd.Id)
        {
            prd.Count = Convert.ToDecimal(item.Split('-')[1]);
            products.Add(prd);
        }
    }

}
#endregion

            ViewBag.Products = products;
            ViewBag.CareersPage = true;
            ViewBag.Blogs = db.Blog.Where(c => c.isActive).OrderByDescending(c => c.PostDate).Take(3).ToList();
            ViewBag.Address = db.Layout.FirstOrDefault().Address;
            ViewBag.Phone = db.Layout.FirstOrDefault().Phone;
            ViewBag.Email = db.Layout.FirstOrDefault().Email;
            ViewBag.FooterLogo = db.Layout.FirstOrDefault().LogoFooter;
            ViewBag.HeaderLogo = db.Layout.FirstOrDefault().Logo;
            Vacancy xdb = db.Vacancies.Include("Admin").Include("Admin.AdminSettings").FirstOrDefault(c => c.isActive&&c.Id==id);

            return View(xdb);
        }

        public ActionResult Application(int id)
        {

            #region Cart list

            HttpCookie cookieCart = Request.Cookies["Cart"];
            List<string> CartList = new List<string>();
            if (cookieCart != null)
            {
                CartList = cookieCart.Value.Split(',').ToList();
                CartList.RemoveAt(CartList.Count - 1);

                ViewBag.CartList = CartList;
                ViewBag.CartListCount = CartList.Count;
            }
            else
            {
                ViewBag.CartListCount = 0;
            }

            List<Product> products = new List<Product>();

            foreach (var item in CartList)
            {
                foreach (var prd in db.Products.Include("ProductImages").Include("Admin").Include("ProductToCategory").Include("ProductToCategory.ProductCategory").ToList())
                {
                    if (Convert.ToInt32(item.Split('-')[0]) == prd.Id)
                    {
                        prd.Count = Convert.ToDecimal(item.Split('-')[1]);
                        products.Add(prd);
                    }
                }

            }
            #endregion

            ViewBag.Products = products;
            ViewBag.CareersPage = true;
            ViewBag.Blogs = db.Blog.Where(c => c.isActive).OrderByDescending(c => c.PostDate).Take(3).ToList();
            ViewBag.Address = db.Layout.FirstOrDefault().Address;
            ViewBag.Phone = db.Layout.FirstOrDefault().Phone;
            ViewBag.Email = db.Layout.FirstOrDefault().Email;
            ViewBag.FooterLogo = db.Layout.FirstOrDefault().LogoFooter;
            ViewBag.HeaderLogo = db.Layout.FirstOrDefault().Logo;
            Vacancy xdb = db.Vacancies.Include("Admin").Include("Admin.AdminSettings").FirstOrDefault(c => c.isActive && c.Id == id);

            return View(xdb);
        }
    }
}

g-auto/Views/Careers/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model g_auto.Models.Vacancy

@if (Model != null && Model.isActive != false)
{

    Html.RenderPartial("~/Views/Partial/_BreadCromb.cshtml", new g_auto.VM.BreadCromb
    {
        Page = "Vacancy Details",
        HREF = Url.Action("Index", "Careers")
    });

    <section class="gauto-blog-page-area section_70">
        <main>
            <article class="b-post b-post-full" style="background: url(/Assets/img/bg-2.png) 50% 100% no-repeat;" data-aos="fade-up">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-10 offset-xl-1">
                            <div class="entry-media">
                                <a class="js-zoom-images" href="~/Uploads/@Model.CoverImage"><img class="img-fluid" src="~/Uploads/@Model.CoverImage" style="width:100%" alt="photo"></a>
                                <div class="blog-decor"></div>
                            </div>
                            <div class="row justify-content-beetween align-items-baseline">
                                <div class="col-md">
                                    <div class="entry-meta">
                                        <time class="entry-meta__item" datetime="@Model.PostDate.ToString("d MMM, yyyy")"><i class="ic far fa-calendar-alt"></i> @Model.PostDate.ToString("d MMM, yyyy")</time>
                                        <span class="entry-meta__item">
                                            by
                                            <a class="entry-meta__link text-primary mr-4">Autlines</a>
                                        </span>
                                        <span class="entry-meta__item">
                                            <i class="fas fa-calendar-minus"></i> Deadline for Applications: 

                                           
                                            <a class="entry-meta__link text-primary comment-count">@Model.Deadline.ToString("d MMM, yyyy")</a>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-md-auto">
                                    <div class="b-post-soc">
                                        <div class="b-post-soc__title">Share This</div>
                                        <div class="b-post-soc__item"><a class="b-post-soc__link" href="#" target="_blank"><i class="ic fab fa-twitter"></i></a></div>
                                        <div class="b-post-soc__item"><a class="b-post-soc__link" href="#" target="_blank"><i class="ic fab fa-facebook-f"></i></a></div>
                                        <div class="b-post-soc__item"><a class="b-post-soc__link" href="#" target="_blank"><i class="ic fab fa-pinterest-p"></i></a></div>
                                        <div class="b-post-soc__item"><a class="b-post-soc__link" href="#" target="_blank"><i class="ic fab fa-behance"></i></a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="entry-main">
                        <div class="entry-header">
                            <div class="row">
                                <div class="col-xl-10 offset-xl-1">
                                    <h1 class="entry-title">@Model.Title</h1>
                                </div>
                            </div>
                        </div>
                        <div class="entry-content">
                            <div class="row">
                                <div class="col-xl-10 offset-xl-1">
                                    @Html.Raw(Model.Content)

                                </div>
                            </div>


                        </div>
                    </div>
                    <div class="entry-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class=" mb-4 vacancy-footer">
                                    <div class="entry-label mb-3">Last date for application:  @Model.Deadline.ToString("d MMM, yyyy")</div>
                                    <div class="entry-label mb-3">Job salary: @Model.Salary</div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </article>
            <!-- end .post-->

          
        </main>
    </section>
}
else
{

    Html.RenderPartial("~/Views/Partial/_BreadCromb.cshtml", new g_auto.VM.BreadCromb
    {
        Page = "404 Page",
        HREF = Url.Action("Index")
    });


    Html.RenderPartial("~/Views/Partial/_NotFound.cshtml");

}

g-auto/Views/Careers/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model List<g_auto.Models.Vacancy>

@{
    Html.RenderPartial("~/Views/Partial/_BreadCromb.cshtml", new g_auto.VM.BreadCromb
    {
        Page = "Careers",
        HREF = Url.Action("Index", "Careers")
    });
}

<section class="section-offers">
    <div class="section-offers__inner">
       
        <div class="container">
            <div class="text-center"  data-aos="fade-up">
                <div class="ui-title-logo ui-title-logo_dark">AUTLINES</div>
                <h2 class="ui-title ui-title_light text-uppercase">We are hiring</h2>
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <p>Dolore magna aliqua enim ad minim veniam, quis nostrud exercitation aliquip duis aute irure dolorin reprehenderits vol dolore fugiat nulla pariatur excepteur sint occaecat cupidatat.</p>
                    </div>
                </div>
                <div class="b-offers-slider ui-slider_arr-prim js-slider" data-slick="{&quot;slidesToShow&quot;: 3, &quot;slidesToScroll&quot;: 1, &quot;dots&quot;: false, &quot;arrows&quot;: true, &quot;autoplay&quot;: true,   &quot;responsive&quot;: [{&quot;breakpoint&quot;: 992, &quot;settings&quot;: {&quot;slidesToShow&quot;: 1, &quot;slidesToScroll&quot;: 1}}]}">
                    @foreach (g_auto.Models.Vacancy item in Model)
                    {
                        <div class="b-offers">
                            <div class="b-offers__wrap">
                                <div class="b-offers__ic text-primary  flaticon-sedan-car-model"></div>
                                <a href="@Url.Action("Details", "Careers", new { id=item.Id})" class="b-offers__title">@item.Title</a>
                                <div class="b-offers__inner ">
                                    <div class="b-offers__img"><img class="img-scale" src="~/Uploads/@item.CoverImage" alt="photo"></div>
                                    <div class="b-offers__info">@item.Description</div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>